# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88ae62428090060d3917a9154a80c13c4a3708b2c80d38a76c1c8005b0197f579d27d4a104dcf64b20e4a130cc7b6839ce848804e6f6585d0568b8b5eefbd9c2

test:
  secret_key_base: 83f4c3d8b5c8c26828b0da3b303a0188eda42b0e0892883c76e855c64a0aa681b421a0e53e6d948f26a4a20df06dd0022a7f4a74832a14aa83841beb9cd03a26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
